site_name: Django ETL Framework
site_description: A comprehensive Django-based ETL framework for healthcare data migration and complex database transformations
site_author: UHMS Backend Team
site_url: https://click-software-gh.github.io/django-etl/

# Repository
repo_name: Click-Software-GH/django-etl
repo_url: https://github.com/Click-Software-GH/django-etl
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.action.view
  
  icon:
    repo: fontawesome/brands/github
    edit: material/file-edit-outline

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - tables
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            members_order: source
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: true

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - API Reference:
    - Configuration: api/config.md
    - Transformers: api/transformers.md
    - Management Commands: api/commands.md
    - Data Validation: api/validation.md
    - Rollback & Recovery: api/rollback.md
    - Performance Profiling: api/performance.md
  - Migration Guide: migration-guide.md
  - Contributing: contributing.md

# Extra
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Click-Software-GH/django-etl
    - icon: fontawesome/solid/envelope
      link: mailto:etl-support@yourcompany.com

# Copyright
copyright: Copyright &copy; 2025 UHMS Backend Team
