site_name: Django ETL Framework
site_description: A comprehensive Django-based ETL framework for healthcare data migration and complex database transformations
site_author: UHMS Backend Team
site_url: https://click-software-gh.github.io/django-etl/

# Repository
repo_name: Click-Software-GH/django-etl
repo_url: https://github.com/Click-Software-GH/django-etl
edit_uri: edit/main/docs/

# Configuration
theme:
  name: readthedocs
  highlightjs: false  # Disable highlight.js to prevent conflicts with Pygments
  navigation_depth: 4
  collapse_navigation: false
  sticky_navigation: true
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom

# Extensions
markdown_extensions:
  - codehilite:
      guess_lang: false
      use_pygments: true
      pygments_style: default
      linenums: false
  - toc:
      permalink: true
      baselevel: 1
  - admonition
  - tables
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - fenced_code
  - nl2br

# Plugins
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            members_order: source
            separate_signature: true
            show_signature_annotations: true

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - API Reference:
    - Configuration: api/config.md
    - Transformers: api/transformers.md
    - Management Commands: api/commands.md
    - Data Validation: api/validation.md
    - Rollback & Recovery: api/rollback.md
    - Performance Profiling: api/performance.md
  - Migration Guide: migration-guide.md
  - Contributing: contributing.md

# Extra
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Click-Software-GH/django-etl

# Extra CSS for ReadTheDocs styling
extra_css:
  - css/extra.css

# Copyright
copyright: Copyright &copy; 2025 UHMS Backend Team
