# Generated by Django ETL Framework

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MigrationLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transformer",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the transformer that was executed",
                        max_length=100,
                    ),
                ),
                (
                    "run_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="When the migration was executed",
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(help_text="Total execution time in seconds"),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the migration completed successfully",
                    ),
                ),
                (
                    "dry_run",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this was a dry run (no actual changes)",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if the migration failed",
                        null=True,
                    ),
                ),
                (
                    "batch_size",
                    models.IntegerField(
                        blank=True,
                        help_text="Batch size used for processing",
                        null=True,
                    ),
                ),
                (
                    "total_records",
                    models.IntegerField(
                        blank=True,
                        help_text="Total number of records processed",
                        null=True,
                    ),
                ),
                (
                    "statistics_json",
                    models.TextField(
                        blank=True,
                        help_text="JSON-encoded statistics about the migration",
                        null=True,
                    ),
                ),
                (
                    "performance_data_json",
                    models.TextField(
                        blank=True,
                        help_text="JSON-encoded performance metrics",
                        null=True,
                    ),
                ),
                (
                    "validation_results_json",
                    models.TextField(
                        blank=True,
                        help_text="JSON-encoded validation results",
                        null=True,
                    ),
                ),
                (
                    "system_info_json",
                    models.TextField(
                        blank=True,
                        help_text="JSON-encoded system information during migration",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Migration Log",
                "verbose_name_plural": "Migration Logs",
                "ordering": ["-run_at"],
            },
        ),
        migrations.CreateModel(
            name="MigrationRunSummary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for this migration session",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the migration session started",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the migration session completed",
                        null=True,
                    ),
                ),
                (
                    "dry_run",
                    models.BooleanField(
                        default=False, help_text="Whether this was a dry run session"
                    ),
                ),
                (
                    "total_transformers",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of transformers in this session",
                    ),
                ),
                (
                    "successful_transformers",
                    models.IntegerField(
                        default=0,
                        help_text="Number of transformers that completed successfully",
                    ),
                ),
                (
                    "failed_transformers",
                    models.IntegerField(
                        default=0, help_text="Number of transformers that failed"
                    ),
                ),
                (
                    "total_records_processed",
                    models.IntegerField(
                        default=0,
                        help_text="Total records processed across all transformers",
                    ),
                ),
                (
                    "user",
                    models.CharField(
                        blank=True,
                        help_text="User who initiated the migration",
                        max_length=100,
                    ),
                ),
                (
                    "command_args",
                    models.TextField(
                        blank=True, help_text="Command line arguments used"
                    ),
                ),
            ],
            options={
                "verbose_name": "Migration Run Summary",
                "verbose_name_plural": "Migration Run Summaries",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="migrationlog",
            index=models.Index(
                fields=["transformer", "run_at"],
                name="django_etl_migrati_transfo_b8e0c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="migrationlog",
            index=models.Index(
                fields=["success", "run_at"],
                name="django_etl_migrati_success_6c4d3e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="migrationlog",
            index=models.Index(
                fields=["dry_run", "run_at"],
                name="django_etl_migrati_dry_run_f8a2b1_idx",
            ),
        ),
    ]
